spring:
  application:
    name: codey

  datasource:
    url: jdbc:mysql://mysql:3306/codey
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Cosmo@123

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082

codex:
  base-url: http://codex:8086

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
